id: P010342
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG12979
  title: བྱམས་ཆོས་བསྐྱར་ཞིབ་དྲང་ངེས་མཛེས་རྒྱན།
  author: ''
  volumes:
    743379e7e0234362ae2939143f5829f8:
      image_group_id: I1KG13056
      title: ''
      volume_number: 1
      total_pages: 342
