id: P010342
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-19 20:44:59.322885
source_metadata:
  id: bdr:W1KG12979
  title: བྱམས་ཆོས་བསྐྱར་ཞིབ་དྲང་ངེས་མཛེས་རྒྱན།
  author: ''
  volumes:
    743379e7e0234362ae2939143f5829f8:
      image_group_id: I1KG13056
      title: ''
      volume_number: 1
      total_pages: 342
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
